package duchan.entity;
// Generated Oct 30, 2020 2:25:46 PM by Hibernate Tools 4.3.1



/**
 * Banner generated by hbm2java
 */
public class Banner  implements java.io.Serializable {


     private String bannerId;
     private String bannerName;
     private String bannerImage;
     private String title;
     private String bannerLink;

    public Banner() {
    }

	
    public Banner(String bannerId) {
        this.bannerId = bannerId;
    }
    public Banner(String bannerId, String bannerName, String bannerImage, String title, String bannerLink) {
       this.bannerId = bannerId;
       this.bannerName = bannerName;
       this.bannerImage = bannerImage;
       this.title = title;
       this.bannerLink = bannerLink;
    }
   
    public String getBannerId() {
        return this.bannerId;
    }
    
    public void setBannerId(String bannerId) {
        this.bannerId = bannerId;
    }
    public String getBannerName() {
        return this.bannerName;
    }
    
    public void setBannerName(String bannerName) {
        this.bannerName = bannerName;
    }
    public String getBannerImage() {
        return this.bannerImage;
    }
    
    public void setBannerImage(String bannerImage) {
        this.bannerImage = bannerImage;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getBannerLink() {
        return this.bannerLink;
    }
    
    public void setBannerLink(String bannerLink) {
        this.bannerLink = bannerLink;
    }




}


