package duchan.entity;
// Generated Oct 30, 2020 2:25:46 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Blog generated by hbm2java
 */
public class Blog  implements java.io.Serializable {


     private String blogId;
     private String blogName;
     private String blogContent;
     private Date dateCreated;
     private Boolean blogStatus;
     private Set comments = new HashSet(0);

    public Blog() {
    }

	
    public Blog(String blogId) {
        this.blogId = blogId;
    }
    public Blog(String blogId, String blogName, String blogContent, Date dateCreated, Boolean blogStatus, Set comments) {
       this.blogId = blogId;
       this.blogName = blogName;
       this.blogContent = blogContent;
       this.dateCreated = dateCreated;
       this.blogStatus = blogStatus;
       this.comments = comments;
    }
   
    public String getBlogId() {
        return this.blogId;
    }
    
    public void setBlogId(String blogId) {
        this.blogId = blogId;
    }
    public String getBlogName() {
        return this.blogName;
    }
    
    public void setBlogName(String blogName) {
        this.blogName = blogName;
    }
    public String getBlogContent() {
        return this.blogContent;
    }
    
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Boolean getBlogStatus() {
        return this.blogStatus;
    }
    
    public void setBlogStatus(Boolean blogStatus) {
        this.blogStatus = blogStatus;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }




}


