package duchan.entity;
// Generated Oct 30, 2020 2:25:46 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.sql.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private String commentId;
     private Blog blog;
     private Userr userr;
     private String commentContent;
     private Date dateCreated;
     private String parentId;

    public Comment() {
    }

	
    public Comment(String commentId) {
        this.commentId = commentId;
    }
    public Comment(String commentId, Blog blog, Userr userr, String commentContent, Date dateCreated, String parentId) {
       this.commentId = commentId;
       this.blog = blog;
       this.userr = userr;
       this.commentContent = commentContent;
       this.dateCreated = dateCreated;
       this.parentId = parentId;
    }
   
    public String getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(String commentId) {
        this.commentId = commentId;
    }
    public Blog getBlog() {
        return this.blog;
    }
    
    public void setBlog(Blog blog) {
        this.blog = blog;
    }
    public Userr getUserr() {
        return this.userr;
    }
    
    public void setUserr(Userr userr) {
        this.userr = userr;
    }
    public String getCommentContent() {
        return this.commentContent;
    }
    
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getParentId() {
        return this.parentId;
    }
    
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }




}


