package duchan.entity;
// Generated Oct 30, 2020 2:25:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hotel generated by hbm2java
 */
public class Hotel  implements java.io.Serializable {


     private String hotelId;
     private String hotelName;
     private String city;
     private String descriptions;
     private Float price;
     private String images;
     private Boolean hotelStatus;
     private Set orderHotels = new HashSet(0);
     private Set hotelServices = new HashSet(0);

    public Hotel() {
    }

	
    public Hotel(String hotelId) {
        this.hotelId = hotelId;
    }
    public Hotel(String hotelId, String hotelName, String city, String descriptions, Float price, String images, Boolean hotelStatus, Set orderHotels, Set hotelServices) {
       this.hotelId = hotelId;
       this.hotelName = hotelName;
       this.city = city;
       this.descriptions = descriptions;
       this.price = price;
       this.images = images;
       this.hotelStatus = hotelStatus;
       this.orderHotels = orderHotels;
       this.hotelServices = hotelServices;
    }
   
    public String getHotelId() {
        return this.hotelId;
    }
    
    public void setHotelId(String hotelId) {
        this.hotelId = hotelId;
    }
    public String getHotelName() {
        return this.hotelName;
    }
    
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getDescriptions() {
        return this.descriptions;
    }
    
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }
    public String getImages() {
        return this.images;
    }
    
    public void setImages(String images) {
        this.images = images;
    }
    public Boolean getHotelStatus() {
        return this.hotelStatus;
    }
    
    public void setHotelStatus(Boolean hotelStatus) {
        this.hotelStatus = hotelStatus;
    }
    public Set getOrderHotels() {
        return this.orderHotels;
    }
    
    public void setOrderHotels(Set orderHotels) {
        this.orderHotels = orderHotels;
    }
    public Set getHotelServices() {
        return this.hotelServices;
    }
    
    public void setHotelServices(Set hotelServices) {
        this.hotelServices = hotelServices;
    }




}


