package duchan.entity;
// Generated Oct 30, 2020 2:25:46 PM by Hibernate Tools 4.3.1



/**
 * OrderHotel generated by hbm2java
 */
public class OrderHotel  implements java.io.Serializable {


     private int orderHotelId;
     private Hotel hotel;
     private Orderr orderr;

    public OrderHotel() {
    }

	
    public OrderHotel(int orderHotelId) {
        this.orderHotelId = orderHotelId;
    }
    public OrderHotel(int orderHotelId, Hotel hotel, Orderr orderr) {
       this.orderHotelId = orderHotelId;
       this.hotel = hotel;
       this.orderr = orderr;
    }
   
    public int getOrderHotelId() {
        return this.orderHotelId;
    }
    
    public void setOrderHotelId(int orderHotelId) {
        this.orderHotelId = orderHotelId;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public Orderr getOrderr() {
        return this.orderr;
    }
    
    public void setOrderr(Orderr orderr) {
        this.orderr = orderr;
    }




}


