package duchan.entity;
// Generated Oct 30, 2020 2:25:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Orderr generated by hbm2java
 */
public class Orderr  implements java.io.Serializable {


     private String orderId;
     private Userr userr;
     private String userPhone;
     private Set orderHotels = new HashSet(0);

    public Orderr() {
    }

	
    public Orderr(String orderId) {
        this.orderId = orderId;
    }
    public Orderr(String orderId, Userr userr, String userPhone, Set orderHotels) {
       this.orderId = orderId;
       this.userr = userr;
       this.userPhone = userPhone;
       this.orderHotels = orderHotels;
    }
   
    public String getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }
    public Userr getUserr() {
        return this.userr;
    }
    
    public void setUserr(Userr userr) {
        this.userr = userr;
    }
    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }
    public Set getOrderHotels() {
        return this.orderHotels;
    }
    
    public void setOrderHotels(Set orderHotels) {
        this.orderHotels = orderHotels;
    }




}


