package duchan.entity;
// Generated Oct 30, 2020 2:25:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Servicee generated by hbm2java
 */
public class Servicee  implements java.io.Serializable {


     private String serviceId;
     private String serviceName;
     private String descriptions;
     private Boolean serviceStatus;
     private Float price;
     private Set hotelServices = new HashSet(0);

    public Servicee() {
    }

	
    public Servicee(String serviceId) {
        this.serviceId = serviceId;
    }
    public Servicee(String serviceId, String serviceName, String descriptions, Boolean serviceStatus, Float price, Set hotelServices) {
       this.serviceId = serviceId;
       this.serviceName = serviceName;
       this.descriptions = descriptions;
       this.serviceStatus = serviceStatus;
       this.price = price;
       this.hotelServices = hotelServices;
    }
   
    public String getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }
    public String getDescriptions() {
        return this.descriptions;
    }
    
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }
    public Boolean getServiceStatus() {
        return this.serviceStatus;
    }
    
    public void setServiceStatus(Boolean serviceStatus) {
        this.serviceStatus = serviceStatus;
    }
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }
    public Set getHotelServices() {
        return this.hotelServices;
    }
    
    public void setHotelServices(Set hotelServices) {
        this.hotelServices = hotelServices;
    }




}


