package duchan.entity;
// Generated Oct 30, 2020 2:25:46 PM by Hibernate Tools 4.3.1



/**
 * Setting generated by hbm2java
 */
public class Setting  implements java.io.Serializable {


     private String settingId;
     private String email;
     private String phoneNumber;
     private String logo;
     private String value;

    public Setting() {
    }

	
    public Setting(String settingId, String phoneNumber) {
        this.settingId = settingId;
        this.phoneNumber = phoneNumber;
    }
    public Setting(String settingId, String email, String phoneNumber, String logo, String value) {
       this.settingId = settingId;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.logo = logo;
       this.value = value;
    }
   
    public String getSettingId() {
        return this.settingId;
    }
    
    public void setSettingId(String settingId) {
        this.settingId = settingId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


