package duchan.entity;
// Generated Oct 30, 2020 2:25:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Userr generated by hbm2java
 */
public class Userr  implements java.io.Serializable {


     private String userId;
     private String userName;
     private String userSex;
     private String userAddress;
     private String userEmail;
     private String userPhone;
     private String userPassword;
     private Boolean userStatus;
     private Set orderrs = new HashSet(0);
     private Set comments = new HashSet(0);

    public Userr() {
    }

	
    public Userr(String userId) {
        this.userId = userId;
    }
    public Userr(String userId, String userName, String userSex, String userAddress, String userEmail, String userPhone, String userPassword, Boolean userStatus, Set orderrs, Set comments) {
       this.userId = userId;
       this.userName = userName;
       this.userSex = userSex;
       this.userAddress = userAddress;
       this.userEmail = userEmail;
       this.userPhone = userPhone;
       this.userPassword = userPassword;
       this.userStatus = userStatus;
       this.orderrs = orderrs;
       this.comments = comments;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserSex() {
        return this.userSex;
    }
    
    public void setUserSex(String userSex) {
        this.userSex = userSex;
    }
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public Boolean getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(Boolean userStatus) {
        this.userStatus = userStatus;
    }
    public Set getOrderrs() {
        return this.orderrs;
    }
    
    public void setOrderrs(Set orderrs) {
        this.orderrs = orderrs;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }




}


